import { DEFAULT_CONFIG, canAddProduct, canUseMonthly, monthKey, monthlyRemaining, toEntitlement, toPlanConfig } from './plan-limits';

const ON = { ...DEFAULT_CONFIG, paywallEnabled: true };
console.assert(canAddProduct(49, false, ON) === true, '무료 49개 → 추가 가능');
console.assert(canAddProduct(50, false, ON) === false, '무료 50개 → 추가 불가');
console.assert(canAddProduct(500, true, ON) === true, '유료는 무제한');
console.assert(canAddProduct(500, false, DEFAULT_CONFIG) === true, '스위치 꺼짐 → 누구나 무제한');
console.assert(canUseMonthly(4, false, ON) === true && canUseMonthly(5, false, ON) === false, '월 5회');
console.assert(canUseMonthly(99, true, ON) === true, '유료 월 무제한');
console.assert(canUseMonthly(99, false, DEFAULT_CONFIG) === true, '스위치 꺼짐 → 월 무제한');
console.assert(monthlyRemaining(1, false, ON) === 4 && monthlyRemaining(5, false, ON) === 0 && monthlyRemaining(9, false, ON) === 0, '남은 횟수(0 아래로 안 감)');
console.assert(monthlyRemaining(1, true, ON) === null && monthlyRemaining(1, false, DEFAULT_CONFIG) === null, '유료·스위치 꺼짐 → 남은 횟수 안내 없음');
console.assert(canAddProduct(39, false, { ...ON, productLimit: 40 }) === true, '서버에서 바꾼 한도 숫자 반영');
console.assert(toPlanConfig({ paywall_enabled: true, product_limit: 50, monthly_limit: 10 }).productLimit === 50, '서버 행 변환');
console.assert(monthKey(new Date(2026, 0, 31, 23, 59)) === '2026-01', '현지 달력 월');
const now = new Date('2026-10-02T00:00:00Z');
const row = (o: object) => ({ ad_free: false, retail_until: null, retail_lifetime: false, retail_source: null, ...o });
console.assert(toEntitlement(row({ retail_until: '2026-10-01T00:00:00Z', retail_source: 'promo' }), now).retailPremium === false, '만료된 이벤트');
console.assert(toEntitlement(row({ retail_until: '2027-04-01T00:00:00Z', retail_source: 'promo' }), now).retailPremium === true, '진행 중 이벤트');
console.assert(toEntitlement(row({ ad_free: true, retail_lifetime: true }), now).retailPremium === true, '테스터 평생');
console.assert(toEntitlement(row({ retail_until: '2026-11-01T00:00:00Z', retail_source: 'subscription' }), now).adFree === true, '매장 구독자는 가정용 광고도 제거');
console.assert(toEntitlement(row({ retail_until: '2026-10-01T00:00:00Z', retail_source: 'subscription' }), now).adFree === false, '구독이 끝나면 광고 제거도 끝');
console.assert(toEntitlement(row({ ad_free: true }), now).adFree === true && toEntitlement(row({ ad_free: true }), now).retailPremium === false, '평생 광고 제거만 산 사람은 매장 유료 아님');
console.log('plan-limits selfcheck OK');
